# Generated by Django 5.0.2 on 2024-02-18 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('admin', 'admin'), ('normal', 'normal'), ('pro', 'pro')], default='normal', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(200)]),
        ),
    ]
