# Generated by Django 5.0.2 on 2024-02-21 06:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_user_type_alter_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='added_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(150)]),
        ),
    ]
